[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mathfuncs"
version = "0.0.1"
description = "Commonly used mathematical functions"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pre-commit",
]

[tool.setuptools.packages.find]
where = ["src/python"]
include = ["mathfuncs*"]

[tool.black]
line-length = 120
target-version = ["py39", "py310", "py311", "py312"]
include = '\.pyi?$'

[tool.isort]
line_length = 120
profile = "black"
known_first_party = ["mathfuncs"]
